name: Run Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Test
        run: dotnet test ./Mittons.Fixtures.Tests.Unit/Mittons.Fixtures.Tests.Unit.csproj --verbosity normal