name: Run Automated Tests

on: [push]

jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup .NET Core SDK 6.0.x
  #       uses: actions/setup-dotnet@v2
  #     - name: Test
  #       run: dotnet test ./Mittons.Fixtures.Tests.Unit/Mittons.Fixtures.Tests.Unit.csproj --verbosity normal
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
      - name: Test
        run: dotnet test ./Mittons.Fixtures.Tests.Integration/Mittons.Fixtures.Tests.Integration.csproj --verbosity normal
  exampe-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v2
      - name: Test
        run: dotnet test ./Mittons.Fixtures.Example/Mittons.Fixtures.Example.csproj --verbosity normal
